### ISSUE TITLE
Binary from Dropbox Account No Longer Available

### ISSUE THREAD

**Issue by dakotahp** [a2ikm/heroku-buildpack-libjpeg62#1]
In `/bin/compile:10` it is fetching a binary from somebody's Dropbox account. Unsurprisingly it is no longer available so is there an alternative source for this file? This buildpack is not functional at this point.

URL:
`https://dl.dropboxusercontent.com/u/469156/heroku-buildpacks/libjpeg62.tar.gz`

**Comment by a2ikm** [comment]
@dakotahp 
It is my Dropbox account, and its public folder has gone.
So I uploaded the binary to GitHub release and updated the URL in the master branch (it was committed as e78caa68).
Could you check it works or not?

**Comment by dakotahp** [comment]
It works! 👍🏼

Domo arigato.

**Comment by a2ikm** [comment]
Thank you 😃
